## Rename names of perimeter grid cells, separated from other data prep as this is massive and inelegant

gridrenam <- function(data,type){
        
        colindex <- which(colnames(data) == type)

data[,colindex] <- ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & (data[,colindex] < 7.608 | data[,colindex] == 896), as.numeric(0),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 7.608 & data[,colindex] < 15.608, as.numeric(1),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 15.608 & data[,colindex] < 31.608, as.numeric(2),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 31.608 & data[,colindex] < 47.608, as.numeric(3),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 47.608 & data[,colindex] < 63.608, as.numeric(4),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 63.608 & data[,colindex] < 79.608, as.numeric(5),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 79.608 & data[,colindex] < 95.608, as.numeric(6),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 95.608 & data[,colindex] < 111.608, as.numeric(7),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 111.608 & data[,colindex] < 127.608, as.numeric(8),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 127.608 & data[,colindex] < 143.608, as.numeric(9),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 143.608 & data[,colindex] < 159.608, as.numeric(10),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 159.608 & data[,colindex] < 175.608, as.numeric(11),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 175.608 & data[,colindex] < 191.608, as.numeric(12),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 191.608 & data[,colindex] < 207.608, as.numeric(13),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 207.608 & data[,colindex] < 215.608, as.numeric(14),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 215.608 & data[,colindex] < 223.215, as.numeric(15),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 223.215 & data[,colindex] <= 224, 16, data[,colindex])))))))))))))))))

data[,colindex] <- ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] == 224, as.numeric(17),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] > 224 & data[,colindex] < 232, as.numeric(18),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 232 & data[,colindex] < 240, as.numeric(19),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 240 & data[,colindex] < 248, as.numeric(20),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 248 & data[,colindex] < 256, as.numeric(21),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 256 & data[,colindex] < 264, as.numeric(22),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 264 & data[,colindex] < 272, as.numeric(23),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 272 & data[,colindex] < 280, as.numeric(24),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 280 & data[,colindex] < 288, as.numeric(25),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 288 & data[,colindex] < 296, as.numeric(26),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 296 & data[,colindex] < 304, as.numeric(27),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 304 & data[,colindex] < 312, as.numeric(28),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 312 & data[,colindex] < 320, as.numeric(29),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 320 & data[,colindex] < 328, as.numeric(30),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 328 & data[,colindex] < 336, as.numeric(31),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 336 & data[,colindex] < 344, as.numeric(32),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 344 & data[,colindex] < 352, as.numeric(33),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 352 & data[,colindex] < 360, as.numeric(34),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 360 & data[,colindex] < 368, as.numeric(35),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 368 & data[,colindex] < 376, as.numeric(36),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 376 & data[,colindex] < 384, as.numeric(37),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 384 & data[,colindex] < 392, as.numeric(38),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 392 & data[,colindex] < 400, as.numeric(39),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 400 & data[,colindex] < 408, as.numeric(40),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 408 & data[,colindex] < 416, as.numeric(41),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 416 & data[,colindex] < 424, as.numeric(42),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 424 & data[,colindex] < 432, as.numeric(43),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 432 & data[,colindex] < 440, as.numeric(44),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 440 & data[,colindex] < 445, as.numeric(45),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 445 & data[,colindex] < 448, as.numeric(46), data[,colindex]))))))))))))))))))))))))))))))

data[,colindex] <-ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 448 & data[,colindex] < 455.608, as.numeric(47),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 455.608 & data[,colindex] < 463.608, as.numeric(48),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 463.608 & data[,colindex] < 479.608, as.numeric(49),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 479.608 & data[,colindex] < 495.608, as.numeric(50),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 495.608 & data[,colindex] < 511.608, as.numeric(51),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 511.608 & data[,colindex] < 527.608, as.numeric(52),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 527.608 & data[,colindex] < 543.608, as.numeric(53),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 543.608 & data[,colindex] < 559.608, as.numeric(54),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 559.608 & data[,colindex] < 575.608, as.numeric(55),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 575.608 & data[,colindex] < 591.608, as.numeric(56),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 591.608 & data[,colindex] < 607.608, as.numeric(57),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 607.608 & data[,colindex] < 623.608, as.numeric(58),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 623.608 & data[,colindex] < 639.608, as.numeric(59),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 639.608 & data[,colindex] < 655.608, as.numeric(60),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 655.608 & data[,colindex] < 663.608, as.numeric(61),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 663.608 & data[,colindex] < 672, as.numeric(62), data[,colindex]))))))))))))))))

data[,colindex] <- ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 672 & data[,colindex] < 676, as.numeric(63),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 676 & data[,colindex] < 680, as.numeric(64),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 680 & data[,colindex] < 688, as.numeric(65),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 688 & data[,colindex] < 696, as.numeric(66),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 696 & data[,colindex] < 704, as.numeric(67),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 704 & data[,colindex] < 712, as.numeric(68),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 712 & data[,colindex] < 720, as.numeric(69),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 720 & data[,colindex] < 728, as.numeric(70),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 728 & data[,colindex] < 736, as.numeric(71),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 736 & data[,colindex] < 744, as.numeric(72),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 744 & data[,colindex] < 752, as.numeric(73),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 752 & data[,colindex] < 760, as.numeric(74),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 760 & data[,colindex] < 768, as.numeric(75),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 768 & data[,colindex] < 776, as.numeric(76),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 776 & data[,colindex] < 784, as.numeric(77),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 784 & data[,colindex] < 792, as.numeric(78),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 792 & data[,colindex] < 800, as.numeric(79),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 800 & data[,colindex] < 808, as.numeric(80),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 808 & data[,colindex] < 816, as.numeric(81),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 816 & data[,colindex] < 824, as.numeric(82),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 824 & data[,colindex] < 832, as.numeric(83),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 832 & data[,colindex] < 840, as.numeric(84),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 840 & data[,colindex] < 848, as.numeric(85),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 848 & data[,colindex] < 856, as.numeric(86),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 856 & data[,colindex] < 864, as.numeric(87),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 864 & data[,colindex] < 872, as.numeric(88),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 872 & data[,colindex] < 880, as.numeric(89),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 880 & data[,colindex] < 888, as.numeric(90),
        ifelse(data$SITE == "NWFN" & data$TRANSECT == "PR" & data[,colindex] >= 888 & data[,colindex] < 896, as.numeric(91), data[,colindex])))))))))))))))))))))))))))))

data[,colindex]

}
