## Rename names of perimeter grid cells, separated from other data prep as this is massive and inelegant

gridrenam <- function(subsurv){

subsurv$STARTNUMBER <- ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & (subsurv$STARTNUMBER < 7.608 | subsurv$STARTNUMBER == 896), "PR0",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 7.608 & subsurv$STARTNUMBER < 15.608, "PR1",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 15.608 & subsurv$STARTNUMBER < 31.608, "PR2",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 31.608 & subsurv$STARTNUMBER < 47.608, "PR3",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 47.608 & subsurv$STARTNUMBER < 63.608, "PR4",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 63.608 & subsurv$STARTNUMBER < 79.608, "PR5",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 79.608 & subsurv$STARTNUMBER < 95.608, "PR6",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 95.608 & subsurv$STARTNUMBER < 111.608, "PR7",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 111.608 & subsurv$STARTNUMBER < 127.608, "PR8",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 127.608 & subsurv$STARTNUMBER < 143.608, "PR9",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 143.608 & subsurv$STARTNUMBER < 159.608, "PR10",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 159.608 & subsurv$STARTNUMBER < 175.608, "PR11",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 175.608 & subsurv$STARTNUMBER < 191.608, "PR12",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 191.608 & subsurv$STARTNUMBER < 207.608, "PR13",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 207.608 & subsurv$STARTNUMBER < 215.608, "PR14",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 215.608 & subsurv$STARTNUMBER < 223.215, "PR15",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 223.215 & subsurv$STARTNUMBER <= 224, "PR16", subsurv$STARTNUMBER)))))))))))))))))

subsurv$STARTNUMBER <- ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER == 224, "PR17",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER > 224 & subsurv$STARTNUMBER < 232, "PR18",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 232 & subsurv$STARTNUMBER < 240, "PR19",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 240 & subsurv$STARTNUMBER < 248, "PR20",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 248 & subsurv$STARTNUMBER < 256, "PR21",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 256 & subsurv$STARTNUMBER < 264, "PR22",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 264 & subsurv$STARTNUMBER < 272, "PR23",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 272 & subsurv$STARTNUMBER < 280, "PR24",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 280 & subsurv$STARTNUMBER < 288, "PR25",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 288 & subsurv$STARTNUMBER < 296, "PR26",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 296 & subsurv$STARTNUMBER < 304, "PR27",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 304 & subsurv$STARTNUMBER < 312, "PR28",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 312 & subsurv$STARTNUMBER < 320, "PR29",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 320 & subsurv$STARTNUMBER < 328, "PR30",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 328 & subsurv$STARTNUMBER < 336, "PR31",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 336 & subsurv$STARTNUMBER < 344, "PR32",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 344 & subsurv$STARTNUMBER < 352, "PR33",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 352 & subsurv$STARTNUMBER < 360, "PR34",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 360 & subsurv$STARTNUMBER < 368, "PR35",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 368 & subsurv$STARTNUMBER < 376, "PR36",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 376 & subsurv$STARTNUMBER < 384, "PR37",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 384 & subsurv$STARTNUMBER < 392, "PR38",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 392 & subsurv$STARTNUMBER < 400, "PR39",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 400 & subsurv$STARTNUMBER < 408, "PR40",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 408 & subsurv$STARTNUMBER < 416, "PR41",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 416 & subsurv$STARTNUMBER < 424, "PR42",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 424 & subsurv$STARTNUMBER < 432, "PR43",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 432 & subsurv$STARTNUMBER < 440, "PR44",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 440 & subsurv$STARTNUMBER < 445, "PR45",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 445 & subsurv$STARTNUMBER < 448, "PR46", subsurv$STARTNUMBER))))))))))))))))))))))))))))))

subsurv$STARTNUMBER <-ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 448 & subsurv$STARTNUMBER < 455.608, "PR47",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 455.608 & subsurv$STARTNUMBER < 463.608, "PR48",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 463.608 & subsurv$STARTNUMBER < 479.608, "PR49",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 479.608 & subsurv$STARTNUMBER < 495.608, "PR50",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 495.608 & subsurv$STARTNUMBER < 511.608, "PR51",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 511.608 & subsurv$STARTNUMBER < 527.608, "PR52",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 527.608 & subsurv$STARTNUMBER < 543.608, "PR53",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 543.608 & subsurv$STARTNUMBER < 559.608, "PR54",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 559.608 & subsurv$STARTNUMBER < 575.608, "PR55",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 575.608 & subsurv$STARTNUMBER < 591.608, "PR56",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 591.608 & subsurv$STARTNUMBER < 607.608, "PR57",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 607.608 & subsurv$STARTNUMBER < 623.608, "PR58",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 623.608 & subsurv$STARTNUMBER < 639.608, "PR59",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 639.608 & subsurv$STARTNUMBER < 655.608, "PR60",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 655.608 & subsurv$STARTNUMBER < 663.608, "PR61",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 663.608 & subsurv$STARTNUMBER < 672, "PR62", subsurv$STARTNUMBER))))))))))))))))

subsurv$STARTNUMBER <- ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 672 & subsurv$STARTNUMBER < 676, "PR63",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 676 & subsurv$STARTNUMBER < 680, "PR64",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 680 & subsurv$STARTNUMBER < 688, "PR65",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 688 & subsurv$STARTNUMBER < 696, "PR66",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 696 & subsurv$STARTNUMBER < 704, "PR67",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 704 & subsurv$STARTNUMBER < 712, "PR68",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 712 & subsurv$STARTNUMBER < 720, "PR69",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 720 & subsurv$STARTNUMBER < 728, "PR70",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 728 & subsurv$STARTNUMBER < 736, "PR71",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 736 & subsurv$STARTNUMBER < 744, "PR72",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 744 & subsurv$STARTNUMBER < 752, "PR73",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 752 & subsurv$STARTNUMBER < 760, "PR74",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 760 & subsurv$STARTNUMBER < 768, "PR75",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 768 & subsurv$STARTNUMBER < 776, "PR76",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 776 & subsurv$STARTNUMBER < 784, "PR77",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 784 & subsurv$STARTNUMBER < 792, "PR78",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 792 & subsurv$STARTNUMBER < 800, "PR79",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 800 & subsurv$STARTNUMBER < 808, "PR80",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 808 & subsurv$STARTNUMBER < 816, "PR81",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 816 & subsurv$STARTNUMBER < 824, "PR82",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 824 & subsurv$STARTNUMBER < 832, "PR83",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 832 & subsurv$STARTNUMBER < 840, "PR84",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 840 & subsurv$STARTNUMBER < 848, "PR85",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 848 & subsurv$STARTNUMBER < 856, "PR86",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 856 & subsurv$STARTNUMBER < 864, "PR87",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 864 & subsurv$STARTNUMBER < 872, "PR88",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 872 & subsurv$STARTNUMBER < 880, "PR89",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 880 & subsurv$STARTNUMBER < 888, "PR90",
        ifelse(subsurv$SITE == "NWFN" & subsurv$TRANSECT == "PR" & subsurv$STARTNUMBER >= 888 & subsurv$STARTNUMBER < 896, "PR91", subsurv$STARTNUMBER)))))))))))))))))))))))))))))

subsurv$STARTNUMBER

}
